order: fix compile error -Werror=unused-result
order.c: In function 'order_register':
order.c:292:5: error: ignoring return value of 'posix_memalign' declared with attribute 'warn_unused_result' [-Werror=unused-result]
  292 |     posix_memalign((void **)&stream_event, ALIGN_SIZE, sizeof(*stream_event));

Signed-off-by: duanery <corcpp@foxmail.com>