trace_helpers: fix compile error -Werror=unused-result
trace_helpers.c: In function 'object_node_new':
trace_helpers.c:448:13: error: ignoring return value of 'asprintf' declared with attribute 'warn_unused_result' [-Werror=unused-result]
  448 |             asprintf(&obj->name_atmnt, "%s @mnt:[%lu]", name, obj->mnt->mntns_ino);

Signed-off-by: duanery <corcpp@foxmail.com>